### ISSUE TITLE
Frameparser does not work with files in different directory

### ISSUE THREAD

**Issue by charlesoblack** [pnxenopoulos/csgo#1]
Running `FrameParser.parse()` on a file that is in a different directory than the one that the python interpreter is in makes it fail. I believe it's due to this line:

https://github.com/pnxenopoulos/csgo/blob/6097857e9bbbbc10a0f680bc9827a71d9984f609/csgo/parser/frameparser.py#L79

e.g. if `demofile` is `/home/user/Desktop/my_demo_file.dem` and the python interpreter is in `/home/user/Git/csgo-stuff` it will actually try to read from `/home/user/Git/csgo-stuff//home/user/Desktop/my_demo_file.dem`.

The specific error I get is:

```
Traceback (most recent call last):

  File "/home/user/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-2-f238148dad71>", line 1, in <module>
    parser.parse()

  File "/home/user/.local/lib/python3.6/site-packages/csgo-0.1-py3.6.egg/csgo/parser/frameparser.py", line 120, in parse
    self._clean_xml()

  File "/home/user/.local/lib/python3.6/site-packages/csgo-0.1-py3.6.egg/csgo/parser/frameparser.py", line 96, in _clean_xml
    tree = ET.parse(self.match_id + ".xml")

  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 1196, in parse
    tree.parse(source, parser)

  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 597, in parse
    self._root = parser._parse_whole(source)

  File "<string>", line unknown
ParseError: syntax error: line 1, column 0
```

**Comment by pnxenopoulos** [comment]
Recent updates should have fixed this problem, please reopen if you are still getting errors.
