### ISSUE TITLE
Around 12-13% of demos fail to parse

### ISSUE THREAD

**Issue by adbok001** [pnxenopoulos/csgo#26]
Out of the 582 matchmaking demos I tried to parse, 74 failed to produce a json file.
There might be a few demos that fail because of #24, but the majority are just normal demo files. When checking out the failing demos sporadically, I noticed a lot of draws, but also other results.

I added four demo files which fail to parse [here](https://github.com/adbok001/demos). Could provide more.

Log=True doesn't help much, it just says "No file produced, error in calling Golang"

**Comment by adbok001** [comment]
Calling parse_demo.go gives more actual error logs:

```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.main()
	/home/libs/csgo/csgo/csgo/parser/parse_demo.go:1716 +0x4085
exit status 2
```

```
INFO: 2021/07/15 01:22:21 parse_demo.go:676: Parsed arguments, reading in /home/demos/003487389747146391760_1227708733.dem and a parse rate of 128 
INFO: 2021/07/15 01:22:21 parse_demo.go:699: Parsed demo header and mesh for map de_mocha 
INFO: 2021/07/15 01:22:21 parse_demo.go:732: Demo is of type GOTV Demo with tickrate 64 
INFO: 2021/07/15 01:22:21 parse_demo.go:733: Demo name is test from /home/demos/003487389747146391760_1227708733.dem
INFO: 2021/07/15 01:22:21 parse_demo.go:734: Registering event handlers, parsing demo
ERROR: 2021/07/15 01:22:21 parse_demo.go:1853: DEMO STREAM ERROR
WARNING: 2021/07/15 01:22:21 parse_demo.go:1854: Demo stream errors can still write output, check for JSON file
ERROR: 2021/07/15 01:22:21 parse_demo.go:1855: runtime error: invalid memory address or nil pointer dereference
stacktrace:
goroutine 18 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/home_remote/docker_home/go/src/runtime/debug/stack.go:24 +0x9f
github.com/markus-wa/demoinfocs-golang/v2/pkg/demoinfocs.NewParserWithConfig.func1(0x8a5b00, 0xc000544380)
	/home/go/pkg/mod/github.com/markus-wa/demoinfocs-golang/v2@v2.9.1/pkg/demoinfocs/parser.go:321 +0x2f
github.com/markus-wa/godispatch.(*Dispatcher).dispatchWithRecover.func1(0xc000184240)
	/home/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:197 +0x6e
panic(0x8a5b00, 0xc000544380)
	/home_remote/docker_home/go/src/runtime/panic.go:965 +0x1b9
github.com/markus-wa/godispatch.callConsumerCode.func1()
	/home/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:122 +0x8b
panic(0x8a5b00, 0xc000544370)
	/home_remote/docker_home/go/src/runtime/panic.go:965 +0x1b9
github.com/markus-wa/godispatch.callConsumerCode.func1()
	/home/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:122 +0x8b
panic(0x8827e0, 0xc7ec50)
	/home_remote/docker_home/go/src/runtime/panic.go:965 +0x1b9
github.com/pnxenopoulos/csgonavparse.(*NavPlace).GetEstimatedCenter(0x0, 0x902d33, 0x9, 0x0, 0x0)
	/home/go/pkg/mod/github.com/pnxenopoulos/csgonavparse@v0.0.0-20200805220556-354c86f74907/nav_place.go:36 +0x4d
main.main.func12()
	/home/libs/csgo/csgo/csgo/parser/parse_demo.go:1529 +0x185
reflect.Value.call(0x865320, 0xc0001843c0, 0x13, 0x901e75, 0x4, 0xc0000a2b00, 0x1, 0x1, 0xc0002265a0, 0x0, ...)
	/home_remote/docker_home/go/src/reflect/value.go:476 +0x8e7
reflect.Value.Call(0x865320, 0xc0001843c0, 0x13, 0xc0000a2b00, 0x1, 0x1, 0xc000558038, 0xd1842f233b6ff401, 0xd100000008010102)
	/home_remote/docker_home/go/src/reflect/value.go:337 +0xb9
github.com/markus-wa/godispatch.callConsumerCode(0x865320, 0xc0001843c0, 0x13, 0xc0000a2b00, 0x1, 0x1)
	/home/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:125 +0x8c
github.com/markus-wa/godispatch.(*Dispatcher).Dispatch(0xc0001842a0, 0x8820c0, 0xcb7c48)
	/home/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:111 +0x258
github.com/markus-wa/demoinfocs-golang/v2/pkg/demoinfocs.(*parser).handleFrameParsed(0xc0001b29a0, 0xcb7c48)
	/home/go/pkg/mod/github.com/markus-wa/demoinfocs-golang/v2@v2.9.1/pkg/demoinfocs/parsing.go:373 +0xa5
reflect.Value.call(0x864d20, 0xc00018a4d0, 0x13, 0x901e75, 0x4, 0xc0000a2f28, 0x1, 0x1, 0xc0001eb560, 0x0, ...)
	/home_remote/docker_home/go/src/reflect/value.go:476 +0x8e7
reflect.Value.Call(0x864d20, 0xc00018a4d0, 0x13, 0xc0000a2f28, 0x1, 0x1, 0xc000118048, 0x58aaa8ab2fdc7f01, 0x5800000006010100)
	/home_remote/docker_home/go/src/reflect/value.go:337 +0xb9
github.com/markus-wa/godispatch.callConsumerCode(0x864d20, 0xc00018a4d0, 0x13, 0xc0000a2f28, 0x1, 0x1)
	/home/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:125 +0x8c
github.com/markus-wa/godispatch.(*Dispatcher).Dispatch(0xc000184240, 0x8533e0, 0xcb7c48)
	/home/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:111 +0x258
github.com/markus-wa/godispatch.(*Dispatcher).dispatchWithRecover(0xc000184240, 0x8533e0, 0xcb7c48)
	/home/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:202 +0x66
github.com/markus-wa/godispatch.(*Dispatcher).dispatchQueue(0xc000184240, 0xc000184300)
	/home/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:177 +0xf4
created by github.com/markus-wa/godispatch.(*Dispatcher).AddQueues
	/home/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:162 +0x148

INFO: 2021/07/15 01:22:21 parse_demo.go:1663: Cleaning data
```

**Comment by pnxenopoulos** [comment]
@adbok001, thanks for being so proactive in finding errors. Nice catch with the draws, that is certainly something to look into. 

I parsed the four demofiles you attached and it looks like the error is occurring at [`parse_demo.go, L1735`](https://github.com/pnxenopoulos/csgo/blob/master/csgo/parser/parse_demo.go#L1735). The error is an index out of range on `currentGame.Rounds[0].TScore = 0`. This means that `currentGame.Rounds` is a list of length 0. However, for this code to fire, the length of rounds must be greater than 0. I suspect that somewhere in between the rounds is being set to an empty list.

I'll look through this more in the morning.

**Comment by pnxenopoulos** [comment]
I think I got it. These seem to be demos from cache, mocha, and so on. Let me try to find the nav files for these. If I cannot find them, then I'll try to throw some sort of error.

**Comment by pnxenopoulos** [comment]
Updated with new nav files, but problems still persist, see #27 for continuation.
