### ISSUE TITLE
Golang error on parse

### ISSUE THREAD

**Issue by pnxenopoulos** [pnxenopoulos/csgo#97]
as per JanEric - 

When parsing all of my own demos i always get this error a couple of times.

The script keeps going and i have not really identified if anything is wrong with the resulting json files (and also dont yet know which demos this affects)

```
panic: runtime error: invalid memory address or nil pointer dereference
stacktrace:
goroutine 41 [running]:
runtime/debug.Stack()
        D:/CSGO/ML/Go/src/runtime/debug/stack.go:24 +0x65
github.com/markus-wa/demoinfocs-golang/v2/pkg/demoinfocs.NewParserWithConfig.func1({0xe4d740, 0xc000ac4d40})
        C:/Users/Jan-Eric/go/pkg/mod/github.com/markus-wa/demoinfocs-golang/v2@v2.12.0/pkg/demoinfocs/parser.go:348 +0x30
github.com/markus-wa/godispatch.(*Dispatcher).dispatchWithRecover.func1()
        C:/Users/Jan-Eric/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:197 +0x42
panic({0xe4d740, 0xc000ac4d40})
        D:/CSGO/ML/Go/src/runtime/panic.go:1038 +0x215
github.com/markus-wa/godispatch.callConsumerCode.func1()
        C:/Users/Jan-Eric/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:122 +0x55
panic({0xe4d740, 0xc000ac4d20})
        D:/CSGO/ML/Go/src/runtime/panic.go:1038 +0x215
github.com/markus-wa/godispatch.callConsumerCode.func1()
        C:/Users/Jan-Eric/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:122 +0x55
panic({0xe2cde0, 0x1279420})
        D:/CSGO/ML/Go/src/runtime/panic.go:1038 +0x215
github.com/markus-wa/demoinfocs-golang/v2/pkg/demoinfocs/common.(*Player).FlashDurationTimeRemaining(0x0)
        C:/Users/Jan-Eric/go/pkg/mod/github.com/markus-wa/demoinfocs-golang/v2@v2.12.0/pkg/demoinfocs/common/player.go:93 +0x1d
github.com/markus-wa/demoinfocs-golang/v2/pkg/demoinfocs/common.(*Player).IsBlinded(...)
        C:/Users/Jan-Eric/go/pkg/mod/github.com/markus-wa/demoinfocs-golang/v2@v2.12.0/pkg/demoinfocs/common/player.go:61
main.main.func24({0xc001e22040, 0x0, 0xc001e1c000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...})
        D:/CSGO/ML/csgo/csgo/parser/parse_demo.go:2162 +0x1530
reflect.Value.call({0xe114e0, 0xc000e98200, 0xc00069ea20}, {0xea2d6a, 0x4}, {0xc0000a3498, 0x1, 0x0})
        D:/CSGO/ML/Go/src/reflect/value.go:543 +0x814
reflect.Value.Call({0xe114e0, 0xc000e98200, 0x0}, {0xc0000a3498, 0x1, 0x1})
        D:/CSGO/ML/Go/src/reflect/value.go:339 +0xc5
github.com/markus-wa/godispatch.callConsumerCode({0xe114e0, 0xc000e98200, 0xe89de0}, {0xc0000a3498, 0x0, 0x10000ffffffffff})
        C:/Users/Jan-Eric/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:125 +0x4a
github.com/markus-wa/godispatch.(*Dispatcher).Dispatch(0xc0000e00c0, {0xe89de0, 0xc00132e640})
        C:/Users/Jan-Eric/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:111 +0x293
github.com/markus-wa/demoinfocs-golang/v2/pkg/demoinfocs.gameEventHandler.dispatch(...)
        C:/Users/Jan-Eric/go/pkg/mod/github.com/markus-wa/demoinfocs-golang/v2@v2.12.0/pkg/demoinfocs/game_events.go:64
github.com/markus-wa/demoinfocs-golang/v2/pkg/demoinfocs.gameEventHandler.playerDeath({0xc0000fe9a0, 0x0, 0xc0000c5440, 0xc0000c5470, 0x0}, 0xb)
        C:/Users/Jan-Eric/go/pkg/mod/github.com/markus-wa/demoinfocs-golang/v2@v2.12.0/pkg/demoinfocs/game_events.go:341 +0x5d3
github.com/markus-wa/demoinfocs-golang/v2/pkg/demoinfocs.newGameEventHandler.func2.1(0xe28200)
        C:/Users/Jan-Eric/go/pkg/mod/github.com/markus-wa/demoinfocs-golang/v2@v2.12.0/pkg/demoinfocs/game_events.go:107 +0x4e
github.com/markus-wa/demoinfocs-golang/v2/pkg/demoinfocs.(*parser).handleGameEvent(0xc0000fe9a0, 0xc001c39680)
        C:/Users/Jan-Eric/go/pkg/mod/github.com/markus-wa/demoinfocs-golang/v2@v2.12.0/pkg/demoinfocs/game_events.go:42 +0xb3
reflect.Value.call({0xe10ca0, 0xc000088610, 0xc0000c5e30}, {0xea2d6a, 0x4}, {0xc0000a3f08, 0x1, 0x0})
        D:/CSGO/ML/Go/src/reflect/value.go:543 +0x814
reflect.Value.Call({0xe10ca0, 0xc000088610, 0x0}, {0xc0000a3f08, 0x1, 0x1})
        D:/CSGO/ML/Go/src/reflect/value.go:339 +0xc5
github.com/markus-wa/godispatch.callConsumerCode({0xe10ca0, 0xc000088610, 0xa62fa5}, {0xc0000a3f08, 0xa63231, 0x0})
        C:/Users/Jan-Eric/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:125 +0x4a
github.com/markus-wa/godispatch.(*Dispatcher).Dispatch(0xc0000e0060, {0xe85ee0, 0xc001c39680})
        C:/Users/Jan-Eric/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:111 +0x293
github.com/markus-wa/godispatch.(*Dispatcher).dispatchWithRecover(0x0, {0xe85ee0, 0xc001c39680})
        C:/Users/Jan-Eric/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:202 +0x5a
github.com/markus-wa/godispatch.(*Dispatcher).dispatchQueue(0xc0000e0060, 0x0)
        C:/Users/Jan-Eric/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:177 +0xb1
created by github.com/markus-wa/godispatch.(*Dispatcher).AddQueues
        C:/Users/Jan-Eric/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:162 +0x193


goroutine 1 [running]:
main.checkError(...)
        D:/CSGO/ML/csgo/csgo/parser/parse_demo.go:2531
main.main()
        D:/CSGO/ML/csgo/csgo/parser/parse_demo.go:2525 +0x2305
exit status 2
```

these demos also cause problems with "clean_rounds" as they only have very few and the rounds the score is always at 0:0. when i open them in csgo demo manager they also show the 0:0 score. interestingly in the overview page of the manager the correct end score is shown

![image](https://user-images.githubusercontent.com/42321130/147858044-b5e8a0c9-53c3-4df3-b057-6e77638425de.png)
![image](https://user-images.githubusercontent.com/42321130/147858047-73aa6506-4415-4e55-aeed-89210dedcd92.png)
![image](https://user-images.githubusercontent.com/42321130/147858048-0b0c9ed5-4896-42a7-a904-3aca2f3c8322.png)

**Comment by pnxenopoulos** [comment]
Golang errors fixed in #94 update. If you don't mind, you can create a new issue with the `clean_rounds` errors and include some more info on the rounds that should be there (namely, start/end tick, score and reasons are most helpful to include).
