### ISSUE TITLE
Golang error on parse

### ISSUE THREAD

**Issue by JanEricNitschke** [pnxenopoulos/csgo#99]
**Describe the bug**
Error from go when parsing specific demo.

**To Reproduce**
Running parser.parse() on the demo in this link.
https://cernbox.cern.ch/index.php/s/ehlO4pjT1j1u4mo

```
panic: runtime error: invalid memory address or nil pointer dereference
stacktrace:
goroutine 10 [running]:
runtime/debug.Stack()
        D:/CSGO/ML/Go/src/runtime/debug/stack.go:24 +0x65
github.com/markus-wa/demoinfocs-golang/v2/pkg/demoinfocs.NewParserWithConfig.func1({0x1371b20, 0xc00143fab0})
        C:/Users/Jan-Eric/go/pkg/mod/github.com/markus-wa/demoinfocs-golang/v2@v2.12.0/pkg/demoinfocs/parser.go:348 +0x30
github.com/markus-wa/godispatch.(*Dispatcher).dispatchWithRecover.func1()
        C:/Users/Jan-Eric/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:197 +0x42
panic({0x1371b20, 0xc00143fab0})
        D:/CSGO/ML/Go/src/runtime/panic.go:1038 +0x215
github.com/markus-wa/godispatch.callConsumerCode.func1()
        C:/Users/Jan-Eric/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:122 +0x55
panic({0x1371b20, 0xc00143faa0})
        D:/CSGO/ML/Go/src/runtime/panic.go:1038 +0x215
github.com/markus-wa/godispatch.callConsumerCode.func1()
        C:/Users/Jan-Eric/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:122 +0x55
panic({0x1351560, 0x17953a0})
        D:/CSGO/ML/Go/src/runtime/panic.go:1038 +0x215
github.com/markus-wa/demoinfocs-golang/v2/pkg/demoinfocs/common.(*Equipment).String(...)
        C:/Users/Jan-Eric/go/pkg/mod/github.com/markus-wa/demoinfocs-golang/v2@v2.12.0/pkg/demoinfocs/common/equipment.go:297
main.parsePlayer(0xc00070b860)
        D:/CSGO/ML/csgo/csgo/parser/parse_demo.go:611 +0x828
main.main.func26({})
        D:/CSGO/ML/csgo/csgo/parser/parse_demo.go:1991 +0x737
reflect.Value.call({0x1336300, 0xc000786080, 0x12c59bd}, {0x13c5947, 0x4}, {0xc0012d56d0, 0x1, 0x1b})
        D:/CSGO/ML/Go/src/reflect/value.go:543 +0x814
reflect.Value.Call({0x1336300, 0xc000786080, 0xc0012d5620}, {0xc0012d56d0, 0x1, 0x1})
        D:/CSGO/ML/Go/src/reflect/value.go:339 +0xc5
github.com/markus-wa/godispatch.callConsumerCode({0x1336300, 0xc000786080, 0x1}, {0xc0012d56d0, 0x0, 0x1})
        C:/Users/Jan-Eric/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:125 +0x4a
github.com/markus-wa/godispatch.(*Dispatcher).Dispatch(0xc00007a120, {0x1350f00, 0x17f4f20})
        C:/Users/Jan-Eric/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:111 +0x293
github.com/markus-wa/demoinfocs-golang/v2/pkg/demoinfocs.(*parser).handleFrameParsed(0xc0001509a0, 0x0)
        C:/Users/Jan-Eric/go/pkg/mod/github.com/markus-wa/demoinfocs-golang/v2@v2.12.0/pkg/demoinfocs/parsing.go:378 +0x8b
reflect.Value.call({0x1335bc0, 0xc00006a670, 0xc000125e30}, {0x13c5947, 0x4}, {0xc0012d5f08, 0x1, 0x0})
        D:/CSGO/ML/Go/src/reflect/value.go:543 +0x814
reflect.Value.Call({0x1335bc0, 0xc00006a670, 0x0}, {0xc0012d5f08, 0x1, 0x1})
        D:/CSGO/ML/Go/src/reflect/value.go:339 +0xc5
github.com/markus-wa/godispatch.callConsumerCode({0x1335bc0, 0xc00006a670, 0xf92fa5}, {0xc0012d5f08, 0xf93231, 0xc0012d9660})
        C:/Users/Jan-Eric/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:125 +0x4a
github.com/markus-wa/godispatch.(*Dispatcher).Dispatch(0xc00007a0c0, {0x13264c0, 0x17f4f20})
        C:/Users/Jan-Eric/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:111 +0x293
github.com/markus-wa/godispatch.(*Dispatcher).dispatchWithRecover(0x0, {0x13264c0, 0x17f4f20})
        C:/Users/Jan-Eric/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:202 +0x5a
github.com/markus-wa/godispatch.(*Dispatcher).dispatchQueue(0xc00007a0c0, 0x0)
        C:/Users/Jan-Eric/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:177 +0xb1
created by github.com/markus-wa/godispatch.(*Dispatcher).AddQueues
        C:/Users/Jan-Eric/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:162 +0x193


goroutine 1 [running]:
main.checkError(...)
        D:/CSGO/ML/csgo/csgo/parser/parse_demo.go:2098
main.main()
        D:/CSGO/ML/csgo/csgo/parser/parse_demo.go:2092 +0x1c15
exit status 2
```

**Comment by pnxenopoulos** [comment]
Fixed in #102
